[project]
name = "royalbistro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "customtkinter>=6.0.0",
    "isort>=9.0.1",
    "pillow>=12.3.0",
    "python-escpos>=3.1",
    "pywin32>=311",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
    "ruff>=0.16.6",
    "ty>=0.0.78",
]
